// Generated by CoffeeScript 2.3.0
var enabled, syntax, tokenizer;

syntax = require('postcss-scss');

tokenizer = require('postcss-scss/lib/scss-tokenize');

enabled = Symbol('scss:enabled');

module.exports = function() {
  return this.transform('.scss', (asset, pack) => {
    var config;
    asset.ext = '.css';
    if (!pack[enabled]) {
      pack[enabled] = true;
      if (config = pack.postcss) {
        config.syntax = syntax;
      }
      pack.tokenize = tokenizer;
    }
  });
};
